name: yolk
description: "Tasks and Habits"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <=4.0.0"

dependencies:
  auth_buttons: 3.0.3
  crypto: 3.0.6
  cupertino_icons: 1.0.8
  envied: 1.0.0
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_launcher_icons: 0.14.2
  get_it: 8.0.3
  go_router: 14.6.2
  google_sign_in: 6.2.2
  injectable: 2.5.0
  sentry_flutter: 8.12.0
  sign_in_with_apple: 6.1.4
  supabase_flutter: 2.8.2
  toastification: 2.3.0

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: 2.4.14
  change_app_package_name: 1.4.0
  envied_generator: 1.0.0
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.2
  very_good_analysis: 7.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Light.ttf
        - asset: fonts/Asap-LightItalic.ttf
          style: italic
        - asset: fonts/Asap-Regular.ttf
        - asset: fonts/Asap-Italic.ttf
          style: italic
        - asset: fonts/Asap-Medium.ttf
        - asset: fonts/Asap-MediumItalic.ttf
          style: italic
        - asset: fonts/Asap-SemiBold.ttf
        - asset: fonts/Asap-SemiBoldItalic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
